import * as React from 'react'
import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  AppBar, Typography, Container, Grid, Button, Switch, Divider,
  Box, Step, Stepper, StepLabel, StepContent, Paper
} from "@mui/material"

import { io } from "socket.io-client";

export default function Home() {
  let socket = null;
  useEffect(() => {
    console.log('useEffect', process.env.serverPort)
    socket = io(`ws://localhost:${process.env.serverPort}`)
    socket.on("hello", (arg) => {
      console.log(arg)
    })

  })

  function handleClick(command) {
    socket.emit('backend_script', command)
  }

  return (
    <div className={styles['container-vertical']}>
      <Head>
        <title>Control Box{process.env.serverPort}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography
          variant="h1"
          noWrap
          component="a"
          href="/"
          sx={{
            mr: 2,
            display: { xs: 'none', md: 'flex' },
            // fontFamily: 'monospace',
            fontWeight: 700,
            letterSpacing: '.3rem',
            color: "#27465c",
            textDecoration: 'none',
          }}
        >
          CONTROL BOX
        </Typography>
        <Divider variant="fullWidth" />
        <div className={styles.container}>
          <Grid container spacing={2}>
            <Grid item xs={12} md>

              <Button variant="linear-pink" onClick={() => { handleClick('ces_service1.sh') }}>

                <Box sx={{ maxWidth: '400' }}>
                  <div>
                    Vehicle Aggregation Service
                  </div>
                  <Divider style={{ background: 'white', margin: '7px 0px' }} />
                  <Stepper activeStep={-1} orientation="vertical">
                    <Step key="1">
                      <StepLabel>Select master blaster campaign settings</StepLabel>
                    </Step>
                    <Step key="2">
                      <StepLabel>Select master blaster campaign settings</StepLabel>
                    </Step>
                    <Step key="3">
                      <StepLabel>Select master blaster campaign settings</StepLabel>
                    </Step>
                  </Stepper>
                </Box>

              </Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-blue" onClick={() => { handleClick('ces_service2.sh') }}>Update Service</Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-pink" onClick={() => { handleClick('ces_enable_sdn.sh') }}>SDN Enable</Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-blue" onClick={() => { handleClick('ces_disable_sdn.sh') }}>SDN Disable</Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-pink" onClick={() => { handleClick('ces_reset.sh') }}>Reset</Button>
            </Grid>
          </Grid>
        </div>

        {/* <Container className={styles['container-vertical']}>
          <div>
            <span>With default Theme:</span>
          </div>
          <Switch {...label} defaultChecked />
          <Switch {...label} />
          <Switch {...label} disabled defaultChecked />
        </Container> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Arenne
          </span>
        </a>
      </footer>
    </div>
  )
}
