import * as React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  AppBar, Typography, Container, Grid, Button, Switch, Divider,
  Box, Step, Stepper, StepLabel, StepContent, Paper
} from "@mui/material"
import CustomButton from '../components/buttons/customButton'
import CommandButton from '../components/buttons/CommandButton';

const label = { inputProps: { "aria-label": "Switch demo" } };
const steps = [
  'Select master blaster campaign settings',
  'Create an ad group',
  'Create an ad',
];



export default function Home() {
  return (
    <div className={styles['container-vertical']}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography
          variant="h1"
          noWrap
          component="a"
          href="/"
          sx={{
            mr: 2,
            display: { xs: 'none', md: 'flex' },
            // fontFamily: 'monospace',
            fontWeight: 700,
            letterSpacing: '.3rem',
            color: "#27465c",
            textDecoration: 'none',
          }}
        >
          CONTROL BOX
        </Typography>
        <Divider variant="fullWidth" />
        <div className={styles.container}>
          <Grid container spacing={2}>
            <Grid item xs={12} md>

              <Button variant="linear-pink" onClick={() => { alert('1') }}>

                <Box sx={{ maxWidth: '400' }}>
                  <div>
                    BUTTON 1
                  </div>
                  <Divider style={{ background: 'white', margin: '7px 0px' }} />
                  <Stepper activeStep={-1} orientation="vertical">
                    <Step key="1">
                      <StepLabel>Select master blaster campaign settings</StepLabel>
                    </Step>
                    <Step key="2">
                      <StepLabel>Select master blaster campaign settings</StepLabel>
                    </Step>
                    <Step key="3">
                      <StepLabel>Select master blaster campaign settings</StepLabel>
                    </Step>
                  </Stepper>
                </Box>

              </Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-blue">Button 2</Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-pink">Button 3</Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-blue">Button 4</Button>
            </Grid>
            <Grid item xs={12} md>
              <Button variant="linear-pink">Button 5</Button>
            </Grid>
          </Grid>
        </div>

        {/* <Container className={styles['container-vertical']}>
          <div>
            <span>With default Theme:</span>
          </div>
          <Switch {...label} defaultChecked />
          <Switch {...label} />
          <Switch {...label} disabled defaultChecked />
        </Container> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            아렌네
          </span>
        </a>
      </footer>
    </div>
  )
}
